require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InstagramUsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # InstagramUser. As you add validations to InstagramUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InstagramUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all instagram_users as @instagram_users" do
      instagram_user = InstagramUser.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:instagram_users)).to eq([instagram_user])
    end
  end

  describe "GET #show" do
    it "assigns the requested instagram_user as @instagram_user" do
      instagram_user = InstagramUser.create! valid_attributes
      get :show, {:id => instagram_user.to_param}, valid_session
      expect(assigns(:instagram_user)).to eq(instagram_user)
    end
  end

  describe "GET #new" do
    it "assigns a new instagram_user as @instagram_user" do
      get :new, {}, valid_session
      expect(assigns(:instagram_user)).to be_a_new(InstagramUser)
    end
  end

  describe "GET #edit" do
    it "assigns the requested instagram_user as @instagram_user" do
      instagram_user = InstagramUser.create! valid_attributes
      get :edit, {:id => instagram_user.to_param}, valid_session
      expect(assigns(:instagram_user)).to eq(instagram_user)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new InstagramUser" do
        expect {
          post :create, {:instagram_user => valid_attributes}, valid_session
        }.to change(InstagramUser, :count).by(1)
      end

      it "assigns a newly created instagram_user as @instagram_user" do
        post :create, {:instagram_user => valid_attributes}, valid_session
        expect(assigns(:instagram_user)).to be_a(InstagramUser)
        expect(assigns(:instagram_user)).to be_persisted
      end

      it "redirects to the created instagram_user" do
        post :create, {:instagram_user => valid_attributes}, valid_session
        expect(response).to redirect_to(InstagramUser.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved instagram_user as @instagram_user" do
        post :create, {:instagram_user => invalid_attributes}, valid_session
        expect(assigns(:instagram_user)).to be_a_new(InstagramUser)
      end

      it "re-renders the 'new' template" do
        post :create, {:instagram_user => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested instagram_user" do
        instagram_user = InstagramUser.create! valid_attributes
        put :update, {:id => instagram_user.to_param, :instagram_user => new_attributes}, valid_session
        instagram_user.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested instagram_user as @instagram_user" do
        instagram_user = InstagramUser.create! valid_attributes
        put :update, {:id => instagram_user.to_param, :instagram_user => valid_attributes}, valid_session
        expect(assigns(:instagram_user)).to eq(instagram_user)
      end

      it "redirects to the instagram_user" do
        instagram_user = InstagramUser.create! valid_attributes
        put :update, {:id => instagram_user.to_param, :instagram_user => valid_attributes}, valid_session
        expect(response).to redirect_to(instagram_user)
      end
    end

    context "with invalid params" do
      it "assigns the instagram_user as @instagram_user" do
        instagram_user = InstagramUser.create! valid_attributes
        put :update, {:id => instagram_user.to_param, :instagram_user => invalid_attributes}, valid_session
        expect(assigns(:instagram_user)).to eq(instagram_user)
      end

      it "re-renders the 'edit' template" do
        instagram_user = InstagramUser.create! valid_attributes
        put :update, {:id => instagram_user.to_param, :instagram_user => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested instagram_user" do
      instagram_user = InstagramUser.create! valid_attributes
      expect {
        delete :destroy, {:id => instagram_user.to_param}, valid_session
      }.to change(InstagramUser, :count).by(-1)
    end

    it "redirects to the instagram_users list" do
      instagram_user = InstagramUser.create! valid_attributes
      delete :destroy, {:id => instagram_user.to_param}, valid_session
      expect(response).to redirect_to(instagram_users_url)
    end
  end

end
